export const exerciseNames = [
  "Agachamento",
  "Supino",
  "Levantamento Terra",
  "Flexões",
  "Barra Fixa",
  "Remada",
  "Rosca Direta",
  "Desenvolvimento de Ombro",
  "Leg Press",
  "Cadeira Extensora",
  "Mergulho",
  "Abdominais",
  "Avanço",
  "Prancha",
  "Curl de Bíceps",
  "Tríceps Pulley",
  "Puxada Alta",
  "Elevação Lateral",
  "Cadeira Abdutora",
  "Cadeira Adutora",
  "Prensa",
  "Crossover",
  "Flexão de Quadril",
  "Stiff",
  "Flexão de Braço Declinada",
  "Agachamento Sumô",
  "Leg Extension",
  "Hip Thrust",
  "Tríceps Testa",
  "Elevação de Panturrilha",
  "Remada Alta",
  "Pulldown",
  "Elevação Frontal",
  "Curl Concentrado",
  "Prancha Lateral",
  "Flexão de Braço na Parede",
  "Curl Martelo",
  "Extensão de Tríceps",
  "Puxada na Corda",
  "Elevação de Gêmeos",
  "Elevação de Pelve",
  "Rosca Alternada",
  "Leg Curl",
  "Elevação de Pernas",
  "Encolhimento de Ombros",
  "Rosca Inversa",
  "Cadeira Flexora",
  "Afundo",
  "Agachamento Bulgáro",
  "Barra Fixa Pronada",
  "Barra Fixa Supinada",
  "Crucifixo",
  "Tríceps Testa na Corda",
  "Elevação de Gêmeos Sentado",
  "Cadeira Flexora Unilateral",
  "Prensa 45 Graus",
  "Rosca Scott",
  "Leg Press 45 Graus",
  "Remada Baixa",
  "Elevação de Panturrilha no Leg Press",
  "Elevação de Quadril com Peso",
  "Cadeira Abdutora Unilateral",
  "Cadeira Adutora Unilateral",
  "Stiff com Halteres",
  "Elevação Frontal com Halteres",
  "Elevação Lateral Invertida",
  "Puxada Aberta",
  "Elevação de Panturrilha em Pé",
  "Elevação de Gêmeos com Máquina",
  "Rosca 21",
  "Cadeira Flexora Horizontal",
  "Agachamento Hack",
  "Pulldown Pegada Fechada",
  "Elevação de Gêmeos com Barra",
  "Crossover Invertido",
  "Cadeira Extensora Unilateral",
  "Rosca na Corda",
  "Agachamento Frontal",
  "Leg Press Horizontal",
  "Abdominal Infra",
  "Curl com Cabo",
  "Extensão de Tríceps na Corda",
  "Rosca Direta com Barra W",
  "Crunch na Máquina",
  "Agachamento Isométrico",
  "Supino Inclinado",
  "Mergulho na Máquina",
  "Prancha com Rotação",
  "Tríceps no Banco",
  "Rosca 21 com Halteres",
  "Elevação de Pernas na Barra Fixa",
  "Leg Press 90 Graus",
  "Flexão de Quadril na Máquina",
  "Desenvolvimento Arnold",
  "Elevação Lateral com Cabo",
  "Remada Curvada",
  "Curl Inverso",
  "Cadeira Extensora Drop Set",
  "Rosca Martelo",
  "Tríceps Coice",
  "Elevação Frontal na Polia",
  "Puxada Supinada",
  "Elevação de Pelve com Peso",
  "Prancha com Elevação de Perna",
  "Prensa Unilateral",
  "Agachamento com Salto",
  "Supino Declinado",
  "Mergulho Entre Bancos",
  "Crossover na Máquina",
  "Flexão de Quadril com Peso",
  "Agachamento Smith",
  "Leg Curl Unilateral",
  "Cadeira Extensora na Máquina",
  "Rosca Concentrada",
  "Pulldown Invertido",
  "Elevação de Pernas Declinado",
  "Stiff Unilateral",
  "Tríceps Testa no Smith",
  "Elevação de Gêmeos no Hack",
  "Elevação Lateral Unilateral",
  "Cadeira Abdutora Drop Set",
  "Agachamento Unilateral",
  "Rosca 21 na Máquina",
  "Extensão de Tríceps na Testa",
  "Elevação de Quadril na Polia",
  "Puxada Fechada",
  "Cadeira Adutora Drop Set",
  "Prancha com Elevação de Braço",
  "Curl Alternado",
  "Agachamento com Barra Guiada",
  "Supino Declinado com Halteres",
  "Mergulho Assistido",
  "Crossover na Corda",
  "Flexão de Quadril com Elástico",
  "Tríceps Testa com Halter",
  "Elevação de Pelve na Máquina",
  "Prensa Hack",
];
